### ISSUE TITLE
Colaboración e incorporación de miembro

### ISSUE THREAD

**Issue by cdyurquina** [Reyvenus/devtech-podcast-web#1]
Hola Reyvenus, 

quisiera colaborar con tu proyecto incorporándome como miembro del equipo del podcast DevTech. Para ello agregaré mi información en la tarjeta 1 (izquierda) como se acordó previamente con el equipo. Te adjunto captura del resultado:

![image](https://user-images.githubusercontent.com/79678415/178427338-eb1014be-0b87-4f70-b8c8-bae2ee465f73.png)

Saludos!

C.Y.

**Comment by Reyvenus** [comment]
Confirrmado, saludos
