### ISSUE TITLE
Añadir Perfil lado derecho en las tajetas

### ISSUE THREAD

**Issue by ValleGalan** [Reyvenus/devtech-podcast-web#3]
Buenas dias Lui , me gustaria agregarme como un integrante de tu equipo . Voy a estar añadiendo mi perfil en el lado "derecho" como acordamos previamente. Saludos :D

**Comment by ValleGalan** [comment]
Asi quedaria al añadir los cambios:
![image](https://user-images.githubusercontent.com/77822150/179239445-fa142001-7e25-4490-995b-5c0bde453b93.png)

**Comment by Reyvenus** [comment]
Hola Flor, dale me parece perfecto👌.... saludos
